exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('assassins').del()
    .then(function() {
      // Inserts seed entries
      return knex('assassins').insert([{
          full_name: 'Alexander Duggan',
          codename: 'The Jackal',
          weapon: 'Sniper rifle',
          contact: 'Jackal@gmail.com',
          age: 31,
          price: 45,
          rating: 7.5,
          kills: 28,
        },
        {
          full_name: 'Anton Chigurh',
          codename: 'Old Man',
          weapon: 'Pneumatic bolt gun',
          contact: 'pneujackcity@gmail.com',
          age: 52,
          price: 40,
          rating: 9,
          kills: 72,
        },
        {
          codename: 'Ghost Dog',
          weapon: 'pistol',
          contact: 'ghostdog@gmail.com',
          age: 28,
          price: 20,
          rating: 6.5,
          kills: 35,
        },
        {
          full_name: 'Jason Bourne',
          weapon: 'parkour',
          contact: 'jb@gmail.com',
          age: 27,
          price: 25,
          rating: 7,
          kills: 48,
        },
        {
          full_name: 'John Wick',
          codename: 'Baba Yaga',
          weapon: 'lots of guns',
          contact: 'babayaga@gmail.com',
          age: 35,
          price: 50,
          rating: 9.5,
          kills: 433,
        },
        {
          full_name: 'Jules Winnfield',
          weapon: 'pistol',
          contact: 'bmf@gmail.com',
          age: 26,
          price: 15,
          rating: 6.5,
          kills: 13,
        },
        {
          full_name: 'Leon',
          codename: 'The Professional',
          weapon: 'everything',
          contact: 'leon@gmail.com',
          age: 41,
          price: 30,
          rating: 8.5,
          kills: 87,
        },
        {
          full_name: 'Nikita Mears',
          codename: 'La Femme Nikitta, Nikitta ',
          weapon: 'silenced pistols',
          contact: 'nikita@gmail.com',
          age: 28,
          price: 30,
          rating: 7,
          kills: 32,
        },
        {
          full_name: 'Pickle Rick',
          codename: 'Solyena',
          weapon: 'lasers and office supplies',
          contact: 'rsanchez@gmail.com',
          age: 60,
          price: 0,
          rating: 8,
          kills: 24,
        },
      ]);
    });
};
